name = "UniformMPS"
version = "0.1.0"

[compat]
julia = "1.12"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OptimKit = "77e91f04-9b3b-57a6-a776-40b61faaebe0"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
VectorInterface = "409d34a3-91d5-4945-b6ec-7529ddf182d8"
